### ISSUE TITLE
Consider relicensing QNotifications to LGPLv3?

### ISSUE THREAD

**Issue by ccordoba12** [dschreij/QNotifications#13]
Hi,

I'm the maintainer of the [Spyder](https://github.com/spyder-ide/spyder) project. We'd really like to use your fantastic project to offer in-app notifications to our users instead of modal dialogs. However, given that Spyder is licensed MIT and yours GPL, we are not able to do that at the moment.

So I'm kindly asking you if you could consider relicensing QNotifications to be LGLPv3, which would retain most of the benefits of the GPL license but would allow us to import it in Spyder. Of course, if we find improvements or additions that could benefit your users, we'd be more than happy to contribute them back to QNotifications.

Besides, I'd like to mention that we created and maintain several important projects for the PyQt/PySide community (such as [Qtpy](https://github.com/spyder-ide/qtpy) and [QtAwesome](https://github.com/spyder-ide/qtawesome)) and help other organizations to maintain their projects as well (e.g. [QtConsole](https://github.com/jupyter/qtconsole), the [Python Language Server](https://github.com/palantir/python-language-server) and [QDarkStyle](https://github.com/ColinDuquesnoy/QDarkStyleSheet)). I'm bringing this point just to let you know that we're always glad to collaborate with other projects instead of reinventing the wheel again and again.

Hope to hear from you soon,
Carlos

**Comment by dschreij** [comment]
Hi Carlos,

I think we have 'met' before. I am an avid user of Spyder and the related packages you describe and maintain a few feedstocks on conda-forge too. I have no concerns at all with changing the license for QNotifications. I chose the GPLv3 license because I thought it was the least restrictive license at that time, but if that is not the case (any longer) then I can change it to an even less restrictive one such as MIT or LGPLv3.

I do have to admit I am a bad maintainer at the moment. My available time to spend on open source side projects has sadly decreased quite a bit since we have a little one running around the house. So even though the state of QNotifications is currently very stable and it does what it has to do, I don't know how responsive I can be to fix any issues if they arise. I just wanted you to know this for your considerations to use this library. For the rest, I am quite honored you'd like to use it for a project such as Spyder :) and if it makes thing easier to make you or anyone else a collaborator on this project I am of course more than willing to do so.

I'll change the license to LGPLv3 and issue a new release with it shortly.

EDIT: Sorry, I switched the licenses around... It's still early here.

**Comment by dschreij** [comment]
Done in v2.0.5

**Comment by ccordoba12** [comment]
> I think we have 'met' before. I am an avid user of Spyder and the related packages you describe and maintain a few feedstocks on conda-forge too.

Cool!

> I have no concerns at all with changing the license for QNotifications

Thanks a lot for agreeing to do that! I really appreciate it!
